version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'tmob'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'tmob'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'tmob'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"

volumes:
  my-db: